[package]
name = "cpp-interop"
version = "0.1.0"
authors = ["Rocky Warren <1085683+therockstorm@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
