[package]
name = "core"
version = "0.1.0"
authors = ["Rocky Warren <1085683+therockstorm@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
