[package]
name = "connection-handler"
version = "0.0.1"
edition = "2018"

[dependencies]
aws_lambda_events = "0.3"
lambda_runtime = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
