[package]
name = "pvs"
version = "0.1.0"
authors = ["Rocky Warren <1085683+therockstorm@users.noreply.github.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
quick-xml = { version = "0.20", features = [ "serialize" ] }
serde = { version = "1.0", features = ["derive"] }
